---
- hosts: webservers
  become: true

  # vars: 
  #  webserver_message: "This is from Apache2 server"

  tasks:  
    - name: start apache2
      service: 
        name=apache2
        state=started

    - name: create index.html using jinja2
      template: 
        src: index.j2
        dest: /var/www/html/index.html

